### ISSUE TITLE
Project Plan - the Virtual Girlfriend Initiative

### ISSUE THREAD

**Issue by rachit-j** [rachit-j/Rackets-Blog#3]
### Project Description
There are many modern applications to the use of artificial intelligence. Especially after the release of OpenAI's Chat models and their DALLE image models, AI has become very popular in the modern society.

Many people use AI for different things. For example, some people use it to get code reviews:

![image](https://github.com/rachit-j/Rackets-Blog/assets/56803677/f0e3e96c-c2d9-4d85-a902-3c9360b99a71)

Other people use it for getting advice on what to write:

![image](https://github.com/rachit-j/Rackets-Blog/assets/56803677/0067c0ed-20ca-49ac-a776-65d5a84eef19)

And finally, some people use it to try to get a girlfriend. Sadly, that does not always work.

![image](https://github.com/rachit-j/Rackets-Blog/assets/56803677/a7aa5f6c-a78a-4b8b-86f8-4d801f32aac1)

However, in this project, we target AI integration into live web development with a finely tuned model that will relieve your sadness by giving you a virtual girlfriend. This project aims to help people who cannot or are incapable of getting a girlfriend because they have given up. These poor souls do not remember the joy of girlfriends anymore and are stuck in a permanent state of sadness. To relieve this issue, we introduce the virtual girlfriend project!

### Project Plan
- [ ] OPTIONAL (step 0): get a girlfriend
- [ ] Step 1: Set up Node.js and jupyter notebook
- [ ] Step 2: Start inputting the framework and baseline code for the model by the end of the period TUESDAY
- [ ] Step 3: Tuesday night fine tune the model and give it the girlfriend properties my friends are looking for (obviously not me)
- [ ] Step 4: Create a presentation where we demo our findings to see if we can actually make a virtual girlfriend to make people happy
- [ ] Step 5: Present
- [ ] OPTIONAL (step 6): make the project so good that men only want a virtual girlfriend

**NOTE: all of this is hypothetical. I am not a depressed asian man looking for a girlfriend. This is a meme.**
